package com.ecs160.hw1;

import com.google.gson.*;
import java.sql.Timestamp;
import java.time.Instant;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class Json_file_parser {
    public List<Post> json_parser(String filePath) throws Exception {
        List<Post> posts = new ArrayList<>();

        InputStream inputStream = getClass().getClassLoader().getResourceAsStream(filePath);
        if (inputStream == null) {
            throw new NullPointerException("File not found in classpath: " + filePath);
        }
        Reader reader = new InputStreamReader(inputStream);
        JsonElement element = JsonParser.parseReader(reader);

        if (element.isJsonObject()) {
            JsonObject jsonObject = element.getAsJsonObject();
            JsonArray feedArray = jsonObject.get("feed").getAsJsonArray();

            for (JsonElement feedObject : feedArray) {
                if (feedObject.getAsJsonObject().has("thread")) {
                    JsonObject threadObject = feedObject.getAsJsonObject().getAsJsonObject("thread");
                    Post post = parsePost(threadObject.getAsJsonObject("post"), null);

                    if (threadObject.has("replies")) {
                        parseReplies(threadObject.getAsJsonArray("replies"), post);
                    }

                    posts.add(post);
                }
            }
        } else {
            throw new IllegalArgumentException("Invalid JSON structure: Expected a JSON object.");
        }
        return posts;
    }

    private Post parsePost(JsonObject postObject, Integer parentPostId) {

        String content = postObject.getAsJsonObject("record").get("text").getAsString();
        int postId;
        if (parentPostId == null) {
            postId = UUID.randomUUID().toString().hashCode();
        } else {
            postId = (content + parentPostId).hashCode();
        }
        // post_id is generated by hashing the content of the post this way we can have unique post_id
        String createdStr = postObject.getAsJsonObject("record").get("createdAt").getAsString();
        Timestamp createdTime = Timestamp.from(Instant.parse(createdStr));
        int wordCount = content.split("\\s+").length;

        return new Post(postId, content, createdTime, wordCount);
    }

    private void parseReplies(JsonArray repliesArray, Post parentPost) {
        for (JsonElement replyElement : repliesArray) {
            JsonObject replyObject = replyElement.getAsJsonObject().getAsJsonObject("post");

            Post reply = parsePost(replyObject, parentPost.get_post_Id());

            parentPost.add_reply(reply);

            if (replyElement.getAsJsonObject().has("replies")) {
                parseReplies(replyElement.getAsJsonObject().getAsJsonArray("replies"), reply);
            }
        }
    }
}
